name: finance-forecast-app
description: Finance Forecasting Platform with MLflow, Model Serving, and Multi-User Support

# Command to run the application (Python backend serves React frontend)
command:
  - /bin/bash
  - -c
  - |
    pip install -r requirements.txt && \
    python -m uvicorn backend.main:app --host 0.0.0.0 --port ${PORT:-8000} --workers 4

# Environment variables
# NOTE: Databricks Apps has a hard limit of 4 vCPU / 12GB RAM
# Heavy training is delegated to dedicated cluster via Databricks Jobs
env:
  # MLflow Configuration
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: MLFLOW_EXPERIMENT_NAME
    value: "/Users/${DATABRICKS_USER}/finance-forecasting"
  - name: PYTHONUNBUFFERED
    value: "1"

  # MLflow Optimization (prevent tracker overload with 30 concurrent users)
  - name: MLFLOW_MAX_WORKERS
    value: "1"  # Single writer per job
  - name: MLFLOW_SKIP_CHILD_RUNS
    value: "true"  # Skip HP tuning child runs

  # Hyperparameter Grid Limits (reduces MLflow writes)
  - name: PROPHET_MAX_COMBINATIONS
    value: "3"
  - name: ARIMA_MAX_COMBINATIONS
    value: "4"
  - name: ETS_MAX_COMBINATIONS
    value: "4"
  - name: SARIMAX_MAX_COMBINATIONS
    value: "6"
  - name: XGBOOST_MAX_COMBINATIONS
    value: "3"

  # Unity Catalog Configuration
  - name: UC_CATALOG_NAME
    value: "main"
  - name: UC_SCHEMA_NAME
    value: "default"
  - name: UC_MODEL_NAME_ONLY
    value: "finance_forecast_model"
  - name: UC_MODEL_NAME
    value: "main.default.finance_forecast_model"

  # ==========================================================================
  # MULTI-USER ARCHITECTURE CONFIGURATION
  # ==========================================================================

  # Lakebase PostgreSQL Configuration
  # These will be set by the deployment script or overridden per environment
  - name: LAKEBASE_HOST
    value: ""  # Set during deployment
  - name: LAKEBASE_DATABASE
    value: "forecast"
  - name: LAKEBASE_USER
    value: "forecast_app"
  - name: LAKEBASE_SSL_MODE
    value: "require"

  # Job Delegation Configuration
  - name: ENABLE_CLUSTER_DELEGATION
    value: "true"
  - name: DEDICATED_CLUSTER_ID
    value: ""  # Set during deployment - 64 vCPU cluster for heavy training
  - name: TRAINING_NOTEBOOK_PATH
    value: "/Workspace/finance-forecasting/notebooks/train_models"

  # Job Configuration
  - name: JOB_TIMEOUT_SECONDS
    value: "7200"  # 2 hours max per job
  - name: JOB_MAX_CONCURRENT_RUNS
    value: "10"  # Support 10 concurrent training jobs
  - name: JOB_MAX_RETRIES
    value: "1"

# Permissions required
permissions:
  - workspace_access
  - cluster_access
  - model_serving_access
  - unity_catalog_access
